### ISSUE TITLE
post x entries per month

### ISSUE THREAD

**Issue by Djive** [oof-bar/craft-membership#1]
Hello!

Is it posiblle let say per user group or any other way
To limit user to by able to publish x entries per month...

**Comment by AugustMiller** [comment]
Hey, this sounds like a great use of the plugin, but a bit outside its purview! The reason I say this up front is that there are an infinite number of additional constraints (specific to an application/implementation) that simply can’t be enforced by one plugin.

All the Membership plugin does is allow you to manage capabilities based on a Subscription, not what those capabilities actually mean to the users of an application.

For example, you might make it possible for someone to create Entries in a particular section (i.e. "Classifieds"), but it's still up to you to apply additional rules.

In your case, I'd recommend listening to the [`EVENT_BEFORE_SAVE_ELEMENT` event](https://github.com/craftcms/cms/blob/develop/src/base/Element.php#L206-L232) in your app's Module:

```php
use craft\base\Element;
use craft\elements\Entry;
use craft\events\ModelEvent;
use yii\base\Event;

Event::on(
    Entry::class,
    Element::EVENT_BEFORE_SAVE,
    function (ModelEvent $e) {
        $entry = $e->sender;

        // Don't worry about it if it's an existing Entry!
        if (!$e->isNew) {
            return;
        }

        // Get the Entry's author:
        $author = $entry->getAuthor();

        // Set a default number of Entries they're allowed to have:
        $maxEntries = 3;

        // Allow more for some Members:
        if ($author->isInGroup('powerUsers')) {
            $maxEntries = 10;
        }

        // Set up date constraint, using PHP's date parsing:
        $beginningOfMonth = new \DateTime('first day of this month');

        // Look up Entries matching the criteria:
        $entryCount = Entry::find()
            ->section('mySection')
            ->author($author)
            ->dateCreated(">= {$beginningOfMonth}")
            ->count();

        // Prevent the save only when the author has exhausted their allowed entries:
        $e->isValid = $entryCount < $maxEntries;
    });
```

Of course, you may need to apply more criteria to this Query, to make sure you're counting just the relevant entries (especially if your "entries per month" roll over, etc), and to exclude administrators / CP users from the logic.

This also doesn't take into consideration the front-end aspect of this, like hiding forms + links based on the number of things they've published, but that could be done via a Behavior, or a similar Entry query like the one in the Event handler, above!

Let me know if this tracks!

**Comment by AugustMiller** [comment]
@Djive Holler if you need additional guidance, here—going to close it for now!

Also happy to help on Discord, if you have more general questions about customizing Craft's behavior via Events, etc.
