### ISSUE TITLE
Craft 4 + Commerce 4 Support

### ISSUE THREAD

**Issue by AugustMiller** [oof-bar/craft-membership#4]
Hey! We are actively working on support for the next major version of Craft and Commerce; it should be ready for testing with v4-beta releases in the first week of April. ❤️

**Comment by theurbanu** [comment]
Any update on this?

**Comment by AugustMiller** [comment]
Hey! Sorry for the delay—I have it running locally on Craft/Commerce v4, but haven't had a chance to thoroughly test, or adopt a few changes, i.e. Project Config.

Full disclosure: I am on parental leave through some time in September, so I can't make a guarantee about timeline. Kiddo isn't here _yet_ (due any day, though), so there may be a window in the coming days to at least get a v2.0.0 out with no major changes! 🤞

Thanks for checking in; hope to have an update, soon. 💕

**Comment by AugustMiller** [comment]
Just sat down with this for a moment, and realized there are a couple blocking issues in Commerce:

- In order to adopt the new `FieldLayoutElements` method of including extra information on Subscription pages, Commerce will have to either modernize their templates, or adopt the new universal element editor UI;
- If [that doesn't happen](https://github.com/craftcms/commerce/issues/2818), we can fall back on the legacy `hook` system;
- Starting Subscriptions is [currently broken](https://github.com/craftcms/commerce/pull/2834), due to a bug with the `PaymentForm` population, but I've PR'd a fix;

**Comment by AugustMiller** [comment]
Subscription payment source creation patch has been merged, so we're one step closer!

- https://github.com/craftcms/commerce/pull/2834

**Comment by AugustMiller** [comment]
@pixelbeatcreative Thanks for your patience on this. I've just cut a 2.0.0 release that brings Craft 4 support!

The readme has been overhauled, so it may be worth a quick read; no significant changes, but I've emphasized a few procedural things with respect to configuration.
